title: Jorge Bustos
logo: /assets/yo.jpg
description: I am a Machine Learning Research Engineer passionate about Generative Models applied to vision and audio
# show_downloads: true
theme: jekyll-theme-minimal
